version: '3'
services:

  local:
    ports:
     - "8000:8000"
     - "8080:8080"
    volumes:
     - .:/usr/src/myapp
    image: "drewkhoury/gcp-dev:latest"
    command: >
      bash -c "dev_appserver.py --host 0.0.0.0 --admin_host 0.0.0.0 --port=8080 app.yaml --enable_sendmail --enable_console"

  new-deploy:
    volumes:
     - .:/usr/src/myapp
     - gcloud-config-volume:/root/.config
    image: "google/cloud-sdk:alpine"
    command: >
      bash -c "/usr/src/myapp/deploy/new-deploy.sh"

  re-deploy:
    volumes:
     - .:/usr/src/myapp
     - gcloud-config-volume:/root/.config
    image: "google/cloud-sdk:alpine"
    environment:
     - CLOUDSDK_CORE_PROJECT
    command: >
      bash -c "cd /usr/src/myapp && gcloud app deploy --quiet"

volumes:
  gcloud-config-volume:
    external: true
